#=
    Gating Network for Mixture of Experts (MoE)
    ============================================
    Classifies patients into 3 metabolic types from meal response features:
      1 = Healthy  (normal glucose tolerance)
      2 = IGT      (impaired glucose tolerance)
      3 = T2D      (type 2 diabetes)

    This gating network is the "entrance" to the MoE architecture.  It outputs
    a probability distribution (softmax) over the 3 expert models, which will
    later weight each expert's prediction of glucose-insulin dynamics.

    MoE architecture overview
    ─────────────────────────
    ┌──────────┐     ┌────────────────┐     ┌─────────────────┐
    │ Features │ ──> │ Gating Network │ ──> │ w1, w2, w3      │
    │ (12-dim) │     │ (this file)    │     │ expert weights   │
    └──────────┘     └────────────────┘     └────────┬────────┘
                                                     │
                       ┌─────────────────────────────┼──────────────────────────┐
                       ▼                             ▼                          ▼
                 ┌───────────┐                ┌───────────┐               ┌───────────┐
                 │ Expert 1  │                │ Expert 2  │               │ Expert 3  │
                 │ (Healthy) │                │  (IGT)    │               │  (T2D)    │
                 └─────┬─────┘                └─────┬─────┘               └─────┬─────┘
                       │                            │                           │
                       └────────────────────────────┼───────────────────────────┘
                                                    ▼
                                          ŷ = Σ wᵢ · expertᵢ(x)

    Data source: GenerateAndLabel_VirtualPopulation.jl
      Generates virtual population data with 12 clinical features + ADA labels.
      Optionally includes estimated model parameters (k1, k5, k6) as extra features.

    Dependencies (add to your Julia environment):
      using Pkg
      Pkg.add("Flux")

    Usage:
      # First generate data:
      #   julia GenerateAndLabel_VirtualPopulation.jl
      # Then train:
      include("gating_network.jl")
      predictor, history = train_and_build(joinpath(@__DIR__, "data"))
      # With estimated params as extra features (15 features total):
      predictor, history = train_and_build(joinpath(@__DIR__, "data"); include_estimated_params=true)
=#

using Flux
using Flux: onehotbatch, logitcrossentropy, onecold
using Statistics
using Random
using Printf

# ─── Data helpers ─────────────────────────────────────────────────────────────

"""
    load_data(data_dir)

Load features and labels from CSV files generated by GenerateAndLabel_VirtualPopulation.jl.
"""
function load_data(data_dir::String)
    lines   = readlines(joinpath(data_dir, "features.csv"))
    header  = split(lines[1], ",")
    n, nf   = length(lines) - 1, length(header)
    features = zeros(Float64, n, nf)
    for i in 1:n
        features[i, :] .= parse.(Float64, split(lines[i + 1], ","))
    end

    llines = readlines(joinpath(data_dir, "labels.csv"))
    labels = [parse(Int, strip(l)) for l in llines[2:end]]

    return features, labels
end

"""Z-score normalisation.  Returns normalised data + stats for reuse."""
function znorm(X::AbstractMatrix; μ=nothing, σ=nothing)
    if isnothing(μ)
        μ = vec(mean(X; dims=1))
        σ = vec(std(X; dims=1))
        σ[σ .== 0] .= 1.0
    end
    X_out = (X .- μ') ./ σ'
    return X_out, μ, σ
end

"""Stratified train/test split keeping class balance."""
function split_data(features, labels; test_frac=0.2, seed=42)
    rng       = MersenneTwister(seed)
    classes   = sort(unique(labels))
    train_idx = Int[]
    test_idx  = Int[]
    for c in classes
        idx     = findall(labels .== c)
        shuffle!(rng, idx)
        n_test  = max(1, round(Int, length(idx) * test_frac))
        append!(test_idx,  idx[1:n_test])
        append!(train_idx, idx[n_test+1:end])
    end
    return (features[train_idx, :], labels[train_idx],
            features[test_idx, :],  labels[test_idx])
end

# ─── Network Architecture ────────────────────────────────────────────────────

"""
    build_gating_network(n_features, n_classes; hidden=[128, 64, 32])

Feedforward classifier for deterministic ADA label boundaries.
No dropout — labels are a deterministic function of features.
Outputs *logits* (softmax applied externally).
"""
function build_gating_network(n_features::Int, n_classes::Int; hidden=[128, 64, 32])
    return Chain(
        Dense(n_features => hidden[1], relu),
        Dense(hidden[1] => hidden[2], relu),
        Dense(hidden[2] => hidden[3], relu),
        Dense(hidden[3] => n_classes),           # logits
    )
end

# ─── Training ────────────────────────────────────────────────────────────────

function accuracy(model, X, y)
    ŷ = onecold(model(X), 1:3)
    return mean(ŷ .== y)
end

"""
    compute_class_weights(labels, n_classes) -> Vector{Float32}

Inverse-frequency weights so minority classes (IGT, T2D) get proportionally
higher loss.  Normalised so weights sum to n_classes.
"""
function compute_class_weights(labels, n_classes::Int)
    counts = [Float32(count(==(c), labels)) for c in 1:n_classes]
    inv_freq = 1.0f0 ./ max.(counts, 1.0f0)
    weights = inv_freq ./ sum(inv_freq) .* n_classes
    return weights
end

"""
    weighted_logitcrossentropy(logits, targets, class_weights)

Cross-entropy loss with per-class weights to handle class imbalance.
`class_weights` is length-3 vector; `targets` is one-hot (3 × batch).
"""
function weighted_logitcrossentropy(logits, targets, class_weights)
    # per-sample cross-entropy:  1 × batch
    per_sample = -sum(targets .* Flux.logsoftmax(logits); dims=1)
    # weight each sample by its true class weight:  1 × batch
    # (broadcast avoids Adjoint * OneHotMatrix dispatch ambiguity)
    w = sum(class_weights .* targets; dims=1)
    return mean(per_sample .* w)
end

"""
    train_gating(data_dir; epochs, lr, batch_size, seed)

Full training pipeline.  Returns `(model, μ, σ, history)`.
"""
function train_gating(data_dir::String;
        epochs=1000, lr=5e-4, batch_size=32, seed=42)

    # ── data prep ────────────────────────────────────────────────────────────
    features, labels = load_data(data_dir)
    X_tr, y_tr, X_te, y_te = split_data(features, labels; seed=seed)

    X_tr_n, μ, σ = znorm(Float32.(X_tr))
    X_te_n, _, _  = znorm(Float32.(X_te); μ=μ, σ=σ)

    # Flux expects  (features × samples)
    X_tr_t = Matrix(X_tr_n')
    X_te_t = Matrix(X_te_n')
    y_tr_oh = onehotbatch(y_tr, 1:3)
    y_te_oh = onehotbatch(y_te, 1:3)

    loader = Flux.DataLoader((X_tr_t, y_tr_oh); batchsize=batch_size, shuffle=true)

    # ── class weights for imbalanced data ──────────────────────────────────
    cw = compute_class_weights(y_tr, 3)
    @info "Class weights" healthy=round(cw[1]; digits=2) IGT=round(cw[2]; digits=2) T2D=round(cw[3]; digits=2)

    # ── model ────────────────────────────────────────────────────────────────
    model     = build_gating_network(size(features, 2), 3)
    opt_state = Flux.setup(Adam(lr), model)

    history = Dict(
        "train_loss" => Float64[], "test_loss"  => Float64[],
        "train_acc"  => Float64[], "test_acc"   => Float64[],
    )

    best_test_loss = Inf
    patience       = 1000000       # early-stopping patience (epochs)
    wait           = 0
    best_model     = deepcopy(model)

    # ── loop ─────────────────────────────────────────────────────────────────
    for epoch in 1:epochs
        # train step
        Flux.trainmode!(model)
        for (xb, yb) in loader
            _, grads = Flux.withgradient(model) do m
                weighted_logitcrossentropy(m(xb), yb, cw)
            end
            Flux.update!(opt_state, model, grads[1])
        end

        # eval step
        Flux.testmode!(model)
        trl = weighted_logitcrossentropy(model(X_tr_t), y_tr_oh, cw)
        tel = weighted_logitcrossentropy(model(X_te_t), y_te_oh, cw)
        tra = accuracy(model, X_tr_t, y_tr)
        tea = accuracy(model, X_te_t, y_te)

        push!(history["train_loss"], trl)
        push!(history["test_loss"],  tel)
        push!(history["train_acc"],  tra)
        push!(history["test_acc"],   tea)

        # early stopping
        if tel < best_test_loss
            best_test_loss = tel
            best_model     = deepcopy(model)
            wait = 0
        else
            wait += 1
        end

        if epoch % 25 == 0 || epoch == 1
            @printf("Epoch %3d │ train %.4f  test %.4f │ train %5.1f%%  test %5.1f%%\n",
                    epoch, trl, tel, 100tra, 100tea)
        end

        # stop early if perfect accuracy achieved
        if tra == 1.0 && tea == 1.0
            @info "Perfect accuracy reached at epoch $epoch"
            break
        end

        if wait >= patience
            @info "Early stopping at epoch $epoch (best test loss: $(round(best_test_loss; digits=4)))"
            break
        end
    end

    model = best_model
    Flux.testmode!(model)

    # ── final report ─────────────────────────────────────────────────────────
    final_acc = accuracy(model, X_te_t, y_te)
    @info "Final test accuracy: $(round(100final_acc; digits=1))%"
    print_confusion(model, X_te_t, y_te)

    return model, μ, σ, history
end

# ─── Evaluation ──────────────────────────────────────────────────────────────

function print_confusion(model, X, y)
    ŷ      = onecold(model(X), 1:3)
    names  = ["Healthy", "    IGT", "    T2D"]
    println("\nConfusion matrix (rows = actual, cols = predicted)")
    println("             ", join(lpad.(["Healthy", "IGT", "T2D"], 9)))
    for i in 1:3
        row = [count((ŷ .== j) .& (y .== i)) for j in 1:3]
        println("  $(names[i])  ", join(lpad.(row, 9)))
    end
    println()
end

# ─── GatingPredictor — portable struct for MoE integration ───────────────────

struct GatingPredictor{M}
    model::M
    μ::Vector{Float32}
    σ::Vector{Float32}
end

"""
    predict_gates(gp, features) -> Vector{Float32}

Return expert weights [P(healthy), P(IGT), P(T2D)] for a single patient
described by a 12-element feature vector.
"""
function predict_gates(gp::GatingPredictor, features::AbstractVector)
    x = Float32.(reshape(features, :, 1))
    x_n = (x .- gp.μ) ./ gp.σ
    Flux.testmode!(gp.model)
    return vec(softmax(gp.model(x_n)))
end

"""
    predict_gates_batch(gp, features) -> Matrix{Float32}  (3 × n_patients)

Batch version: `features` is (n_patients × 12).
"""
function predict_gates_batch(gp::GatingPredictor, features::AbstractMatrix)
    X = Float32.(features')                 # 12 × n
    X_n = (X .- gp.μ) ./ gp.σ
    Flux.testmode!(gp.model)
    return softmax(gp.model(X_n))           # 3 × n
end

"""
    classify(gp, features) -> Int

Hard classification (1/2/3) for a single patient.
"""
function classify(gp::GatingPredictor, features::AbstractVector)
    probs = predict_gates(gp, features)
    return argmax(probs)
end

# ─── Convenience: train + wrap ────────────────────────────────────────────────

"""
    train_and_build(data_dir; kw...) -> (GatingPredictor, history)

One-call entry point: trains the gating network and returns a ready-to-use
predictor for the MoE pipeline.
"""
function train_and_build(data_dir::String; kw...)
    model, μ, σ, history = train_gating(data_dir; kw...)
    gp = GatingPredictor(model, Float32.(μ), Float32.(σ))
    return gp, history
end

# ─── Main ────────────────────────────────────────────────────────────────────

if abspath(PROGRAM_FILE) == @__FILE__
    data_dir = joinpath(@__DIR__, "data")
    if !isfile(joinpath(data_dir, "features.csv"))
        @error "No data found. Run GenerateAndLabel_VirtualPopulation.jl first to generate training data."
        exit(1)
    end

    predictor, history = train_and_build(data_dir)

    # quick demo: predict gate weights for the first 5 test patients
    features, labels = load_data(data_dir)
    label_names = ["Healthy", "IGT", "T2D"]
    println("\n── Sample predictions ──")
    for i in 1:min(5, size(features, 1))
        probs = predict_gates(predictor, features[i, :])
        pred  = argmax(probs)
        @printf("Patient %3d │ true: %-7s │ pred: %-7s │ gates: [%.2f, %.2f, %.2f]\n",
                i, label_names[labels[i]], label_names[pred],
                probs[1], probs[2], probs[3])
    end
end
